### ISSUE TITLE
Fix dockerfile tests

### ISSUE THREAD

**Issue by jdahm** [MeteoSwiss-APN/dawn#610] opened 2020-01-16 19:44 UTC
Every commit currently has a red x next to it because a test called "ci/dockercloud (/gtclang/Dockerfile)" is failing. Let's replace that with Travis testing or disable altogether.

**Comment by jdahm** [comment] 2020-01-18 19:51
@cosunae I don't have access to the gtclang user at https://hub.docker.com/u/gtclang. Do you have access? Could someone go in and disable/remove those? Once things settle in the repository I'll have a set of dockerfiles that build up different components of the toolchain, and we can use one of those to deploy there.

**Comment by twicki** [comment] 2020-03-12 14:34
duplicate of https://github.com/MeteoSwiss-APN/dawn/issues/623

**Closed** 2020-03-12 14:34 UTC
Labels: Testing, refactoring, sprint planning
