### ISSUE TITLE
Dependencies during build

### ISSUE THREAD

**Issue by jdahm** [MeteoSwiss-APN/dawn#349] opened 2019-10-15 17:51 UTC
If I build the code with too many threads (e.g. 10), the build fails at some point because certain `pb` files are not yet generated. Restarting the build from there allows the build to finish successfully.

This is probably caused by incorrectly expressing dependencies between the generated files and other sources or directories that use them.

**Comment by havogt** [comment] 2019-10-15 18:02
Duplicate of #323. I tried to fix it but failed... will try again tomorrow.

**Closed by havogt** 2019-10-15 18:02 UTC
Labels: bug
